name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            cd /home/azureuser/prince/Crestwave_Global
            git pull origin main
            docker stop crestwave || true
            docker rm crestwave || true
            docker build -t crestwave .
            docker run -d \
              --name crestwave \
              -p 80:5000 \
              --restart always \
              -e NODE_ENV=production \
              -e PORT=5000 \
              --env-file .env \
              crestwave
            echo "Deployed!"